[build]
builder = "NIXPACKS"
buildCommand = "cd backend && pip install -r requirements.txt && python -c 'from sentence_transformers import SentenceTransformer; SentenceTransformer(\"all-MiniLM-L6-v2\")'"

[deploy]
startCommand = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 60

[env]
PYTHONPATH = "/app/backend"
PYTHON_VERSION = "3.11"

[[services]]
name = "urba-ai-backend"
type = "web"

[services.urba-ai-backend]
port = 8000
